language: csharp
mono: none

matrix:
    include:
        - os: linux
          sudo: required
          dotnet: 1.0.4
          env: 
            - BUILD_FRAMEWORK=netstandard1.3
            - TEST_FRAMEWORK=netcoreapp1.0
        - os: linux
          sudo: required
          dotnet: 2.1.4
          env: 
            - BUILD_FRAMEWORK=netstandard2.0
            - TEST_FRAMEWORK=netcoreapp2.0

before_script:
    - chmod +x ./build/build.sh
    - chmod +x ./build/test.sh

script:
  - ./build/build.sh
  - ./build/test.sh