// <auto-generated />
using Flarine.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Flarine.Database.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20180122142155_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Flarine.Database.Entity.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountId");

                    b.Property<string>("UserId");

                    b.Property<string>("UserSecret");

                    b.HasKey("Id");

                    b.ToTable("tbl_accounts");
                });

            modelBuilder.Entity("Flarine.Database.Entity.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<int>("CostumeId");

                    b.Property<bool>("CostumeVisible");

                    b.Property<int>("FaceId");

                    b.Property<int>("HeroId");

                    b.Property<int>("Level");

                    b.Property<int>("MountTier");

                    b.Property<string>("Name");

                    b.Property<int>("Tradition");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("tbl_heros");
                });

            modelBuilder.Entity("Flarine.Database.Entity.Hero", b =>
                {
                    b.HasOne("Flarine.Database.Entity.Account")
                        .WithMany("AccountHeros")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
